apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata: 
  name: dc-webui
spec: 
  replicas: 1
  selector: 
    dockercoins: webui
  template:
    metadata:
      labels: 
        dockercoins: webui
    spec:
      containers:
        - args:
            - webui.js
          command:
            - node
          env:
            - name: TOKEN
              value: hola que tal          
          image: eleigle/node:express-redis
          name: container-po-webui
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /app/webui.js
              name: volume-po-webui
              readOnly: true
              subPath: webui.js
            - mountPath: /app/files/
              name: volume-po-files
              readOnly: true                      
          workingDir: /app/
      initContainers:
        - args:
            - git clone https://github.com/josecmb/dockercoins-1.git --single-branch -b 2022-03-santander; cp -r ./dockercoins-1/webui/files/* /app/files/  
          command:
            - sh
            - -c
          env:
            - name: TOKEN
              value: hola que tal          
          image: alpine/git:latest
          name: git-container          
          volumeMounts:
            - mountPath: /app/files/
              name: volume-po-files
              readOnly: false                      
            - mountPath: /tmp/
              name: volume-po-tmp
              readOnly: false       
          workingDir: /tmp/          
      volumes:
        - name: volume-po-webui
          secret:
            defaultMode: 0400
            items:
              - key: webui.js
                mode: 0400
                path: webui.js
            secretName: secret-webui
        - name: volume-po-files
          emptydir:
            medium: Memory
            sizeLimit: 2Mi
        - name: volume-po-tmp
          emptydir:
            medium: Memory  
            sizeLimit: 2Mi
