apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: sts-redis
spec: 
  replicas: 1
  selector: 
    matchLabels:
      dockercoins: redis
  serviceName: redis
  template:
    metadata:
      labels: 
        dockercoins: redis
    spec:
      containers:
        -
          args:
            - redis-server 
          command:
            - docker-entrypoint.sh
          env:
            -
              name: TOKEN
              value: hola que tal
          image: redis:latest
          name: container-po-redis
          ports:
            -
              containerPort: 6379
              protocol: TCP
          volumeMounts:
            -
              mountPath: /data/
              name: pvc-redis
              readOnly: false
          workingDir: /data/      
    volumenClaimsTemplate:
      - metadata:
          name: pvc-redis
        spec:
          accessMode:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          volumenMode: Filesystem
      
    
  
